/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    services: Service;
    tags: Tag;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'zh') | ('en' | 'zh')[];
  globals: {
    'about-page': AboutPage;
    'our-team-page': OurTeamPage;
  };
  globalsSelect: {
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'our-team-page': OurTeamPageSelect<false> | OurTeamPageSelect<true>;
  };
  locale: 'en' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 图片替代文字（中英文），有助于 SEO 和无障碍阅读
   */
  alt: string;
  /**
   * 请输入图片分类（如 "portfolio" 或 "team"）。注意：这将作为后台筛选的标签，请尽量保持拼写一致。
   */
  category?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  category: 'commercial' | 'residential';
  location?: string | null;
  year?: string | null;
  featuredImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional project content displayed below the gallery
   */
  content?:
    | (
        | {
            level: 'h2' | 'h3';
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            text: string;
            cite?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  breadcrumb?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  introP1?: string | null;
  introP2?: string | null;
  featuredImage: number | Media;
  sections?:
    | {
        title: string;
        description?: string | null;
        image: number | Media;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary shown on the blog list cards
   */
  excerpt: string;
  featuredImage: number | Media;
  /**
   * Author name (e.g. "Y&Y Team")
   */
  author: string;
  publishedDate: string;
  tags?: (number | Tag)[] | null;
  content: (
    | {
        level: 'h2' | 'h3';
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heading';
      }
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        text: string;
        /**
         * Source/author of the quote (optional)
         */
        cite?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
  )[];
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  location?: T;
  year?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?:
    | T
    | {
        heading?:
          | T
          | {
              level?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              cite?: T;
              id?: T;
              blockName?: T;
            };
      };
  sortOrder?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  breadcrumb?:
    | T
    | {
        label?: T;
        id?: T;
      };
  introP1?: T;
  introP2?: T;
  featuredImage?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  sortOrder?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  publishedDate?: T;
  tags?: T;
  content?:
    | T
    | {
        heading?:
          | T
          | {
              level?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              cite?: T;
              id?: T;
              blockName?: T;
            };
      };
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  header?: {
    title?: string | null;
    breadcrumb?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  sectionTitle?: string | null;
  slogan?: string | null;
  sloganAccent?: string | null;
  /**
   * Team photo shown above the client list
   */
  teamImage?: (number | null) | Media;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  clientsTitle?: string | null;
  clients?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  facilities?:
    | {
        title: string;
        description?: string | null;
        icon: 'facility-1' | 'facility-2';
        id?: string | null;
      }[]
    | null;
  visionMission?: {
    sectionTitle?: string | null;
    sectionSubtitle?: string | null;
    sectionSubtitleAccent?: string | null;
    sectionDescription?: string | null;
    vision?: {
      title?: string | null;
      description?: string | null;
    };
    mission?: {
      title?: string | null;
      description?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-team-page".
 */
export interface OurTeamPage {
  id: number;
  header?: {
    title?: string | null;
    breadcrumb?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  sectionTitle?: string | null;
  subtitle?: string | null;
  subtitleAccent?: string | null;
  description?: string | null;
  groups?:
    | {
        name: string;
        members?:
          | {
              name: string;
              title: string;
              photo: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        title?: T;
        breadcrumb?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  sectionTitle?: T;
  slogan?: T;
  sloganAccent?: T;
  teamImage?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  clientsTitle?: T;
  clients?:
    | T
    | {
        name?: T;
        id?: T;
      };
  facilities?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  visionMission?:
    | T
    | {
        sectionTitle?: T;
        sectionSubtitle?: T;
        sectionSubtitleAccent?: T;
        sectionDescription?: T;
        vision?:
          | T
          | {
              title?: T;
              description?: T;
            };
        mission?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-team-page_select".
 */
export interface OurTeamPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        title?: T;
        breadcrumb?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  sectionTitle?: T;
  subtitle?: T;
  subtitleAccent?: T;
  description?: T;
  groups?:
    | T
    | {
        name?: T;
        members?:
          | T
          | {
              name?: T;
              title?: T;
              photo?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}